name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3
  - pip:
      - seaborn==0.12.2
      - pandas==2.0.3
      - jupyterlab==4.0.7
      - notebook==7.0.6
      - ydata-profiling[notebook]==4.6.0
      - pyarrow==13.0.0
      - wandb==0.15.12
