name: data_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - mlflow=2.6.0
  - requests==2.31.0
  - pip=23.3
  - pip:
      - pandas==2.1.1
      - scikit-learn==1.3.1
      - wandb==0.15.12
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
