name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.6.0
  - ipython=8.16.1
  - notebook=7.0.6
  - jupyterlab=4.0.7
  - cookiecutter=2.4.0
  - hydra-core=1.3
  - matplotlib=3.8.0
  - pandas=2.1.1
  - git=2.42.0
  - pip=23.3
  - pip:
      - wandb==0.15.12
