name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - mlflow=2.6.0
  - git=2.40.1
  - pip=23.3
  - pip:
      - mlflow==2.7.1
      - matplotlib==3.8.0
      - ipython==8.16.1
      - notebook==7.0.6
      - jupyterlab==4.0.7
      - cookiecutter==2.4.0
      - hydra-core==1.3.2
      - pandas==2.1.1
      - wandb==0.15.12
