name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - mlflow=2.6.0
  - pip=23.3
  - pip:
      - pandas==2.1.1
      - scikit-learn==1.3.1
      - matplotlib==3.8.0
      - pillow==10.1.0
      - wandb==0.15.12
